services:
  - type: web
    name: shl-rag-recommendation-engine
    env: python
    runtime: python3
    buildCommand: pip install -r render-requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT --workers 2 --timeout 120 --keep-alive 5 --log-level debug --error-logfile - --access-logfile - main:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: RENDER_EXTERNAL_URL  # This helps with URLs in the application
        fromService:
          name: shl-rag-recommendation-engine
          type: web
          property: host
      - key: RENDER
        value: true
    healthCheckPath: /
    numInstances: 1
    plan: free
    region: oregon  # Choose the region closest to your users
    autoDeploy: true
    staticPublishPath: ./static  # Render will serve static files directly